[project]
name = "sbapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "thestackshepherd", email = "jadenmschwartz00@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.3",
    "psycopg>=3.3.4",
    "sqlalchemy>=2.0.51",
]

[project.scripts]
sbapi = "sbapi:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
